describe('TugasDay4', function(){
    it('Beli HP', function(){
        cy.urlday4()
        cy.get(':nth-child(2) > .card > .card-block > .card-title > .hrefch').click()
        cy.contains('820')
        cy.get('.col-sm-12 > .btn').click()
        cy.get('#cartur').click()
        cy.get('.col-lg-1 > .btn').click()
        cy.get('#name').type('Jaeger').should('have.value','Jaeger')
        cy.wait(1000)
        cy.get('#country').type('Kuvukiland').should('have.value','Kuvukiland')
        cy.wait(1000)
        cy.get('#city').type('Aisen').should('have.value','Aisen')
        cy.wait(1000)
        cy.get('#card').type('00011000011').should('have.value','00011000011')
        cy.wait(1000)
        cy.get('#month').type('April').should('have.value','April')
        cy.wait(1000)
        cy.get('#year').type('2023').should('have.value','2023')
        cy.wait(1000)
        cy.get('#orderModal > .modal-dialog > .modal-content > .modal-footer > .btn-primary').click()
        cy.wait(1000)
        cy.get('.confirm').click()
        cy.wait(1000)
    })
    it('Beli HP1', function(){
        cy.urlday4()
        cy.get(':nth-child(2) > .card > :nth-child(1) > .card-img-top').click()
        cy.contains('820')
        cy.get('.col-sm-12 > .btn').click()
        cy.get('#cartur').click()
        cy.get('.col-lg-1 > .btn').click()
        cy.get('#name').type('Jaeger').should('have.value','Jaeger')
        cy.wait(1000)
        cy.get('#country').type('Kuvukiland').should('have.value','Kuvukiland')
        cy.wait(1000)
        cy.get('#city').type('Aisen').should('have.value','Aisen')
        cy.wait(1000)
        cy.get('#card').type('00011000011').should('have.value','00011000011')
        cy.wait(1000)
        cy.get('#month').type('April').should('have.value','April')
        cy.wait(1000)
        cy.get('#year').type('2023').should('have.value','2023')
        cy.wait(1000)
        cy.get('#orderModal > .modal-dialog > .modal-content > .modal-footer > .btn-primary').click()
        cy.wait(1000)
        cy.get('.confirm').click()
        cy.wait(1000)
    })
})
