describe('Tugas 5', function (){
    it('Case Study 2', function (){
        cy.visit('https://demoqa.com/automation-practice-form/')
        cy.get('#firstName').type('Jaeger').should('have.value','Jaeger')
        cy.get('#lastName').type('Dorn').should('have.value','Dorn')
        cy.get('#userEmail').type('dorn@gmail.com').should('have.value','dorn@gmail.com')
        cy.get('#genterWrapper > .col-md-9 > :nth-child(1)',{force:true}).click().should('be.visible')
        cy.get('#userNumber').type('00011000').should('have.value','00011000')
        cy.get('#dateOfBirthInput').should('have.value','31 Aug 2021')
        cy.get('.subjects-auto-complete__value-container',{force:true}).type('E')
        cy.get('#react-select-2-option-0',{force:true}).click()
        cy.get('#hobbiesWrapper > .col-md-9 > :nth-child(1) > .custom-control-label').click()
        cy.wait(1000)
        cy.get('#hobbiesWrapper > .col-md-9 > :nth-child(2) > .custom-control-label').click()
        cy.wait(1000)
        cy.get('#hobbiesWrapper > .col-md-9 > :nth-child(3) > .custom-control-label').click()
        cy.wait(1000)
        cy.get('#uploadPicture').attachFile('209377413_2706495079652346_3575576564316998897_n.jpg')
        cy.get('#currentAddress').type('Jakarta Timur').should('have.value','Jakarta Timur')
        cy.get('#stateCity-wrapper > :nth-child(2)').type('Haryana')
        cy.get('#react-select-3-option-2',{force:true}).click()
        cy.wait(1000)
        cy.get('#stateCity-wrapper > :nth-child(3)').click().should('be.not.visible')
        cy.get('#submit').should('be.visible').click()
    })
})
