describe('Tugas 5', function (){
    it('Case Study 2', function (){
        cy.visit('https://demoqa.com/automation-practice-form/')
        cy.get('#firstName').type('Jaeger').should('have.value','Jaeger')
        cy.get('#lastName').type('Dorn').should('have.value','Dorn')
        cy.get('#userEmail').type('dorn@gmail.com').should('have.value','dorn@gmail.com')
        cy.get('#genterWrapper > .col-md-9 > :nth-child(1)',{force:true}).click().should('be.visible')
        cy.get('#genterWrapper > .col-md-9 > :nth-child(1) > .custom-control-label').should('have.text','Male')
        cy.get('#userNumber').type('00011000').should('have.value','00011000')
        // cy.get('#dateOfBirthInput').invoke('val','30 Dec 2000').should('have.value','30 Dec 2000')
        cy.get('#dateOfBirthInput',{force:true}).click().type('{selectall}','{backspace}').type('14 Nov 1999').type('{enter}').should('have.value','14 Nov 1999')
        cy.get('.subjects-auto-complete__value-container').type('English{enter}')
        cy.get('#hobbiesWrapper > .col-md-9 > :nth-child(1) > .custom-control-label').click()
        cy.get('#hobbiesWrapper > .col-md-9 > :nth-child(1) > .custom-control-label').should('have.text','Sports')
        cy.get('#hobbiesWrapper > .col-md-9 > :nth-child(2) > .custom-control-label').click()
        cy.get('#hobbiesWrapper > .col-md-9 > :nth-child(2) > .custom-control-label').should('have.text','Reading')
        cy.get('#hobbiesWrapper > .col-md-9 > :nth-child(3) > .custom-control-label').click()
        cy.get('#hobbiesWrapper > .col-md-9 > :nth-child(3) > .custom-control-label').should('have.text','Music')
        cy.wait(800)
        cy.get('#uploadPicture').attachFile('209377413_2706495079652346_3575576564316998897_n.jpg')
        cy.get('#currentAddress').type('Jakarta Timur').should('have.value','Jakarta Timur')
        cy.get('#stateCity-wrapper > :nth-child(2)').type('Haryana{enter}')
        cy.wait(800)
        cy.get('#stateCity-wrapper > :nth-child(3)').type('Karnal{enter}')
        cy.wait(800)
        cy.get('#submit').should('be.visible').click()
        cy.get('.modal-header').should('have.text','Thanks for submitting the form')
        cy.get('tbody > :nth-child(7) > :nth-child(2)').should('have.text','Sports, Reading, Music')
        cy.get('#closeLargeModal').should('have.text','Close').click()
    })
})
